name: xmtp_proto
description: Protobuf client and generated classes for GRPC API
# Version replaced at runtime in dev/dart/prepublish
version: 0.0.0
repository: 'https://github.com/xmtp/proto'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fixnum: ^1.0.0
  grpc: ^3.1.0
  protobuf: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0