# .github/workflows/publish.yml
name: Publish to pub.dev
on:
  push:
    tags:
    # must align with the tag-pattern configured on pub.dev
    - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v'
jobs:
  dart:
    # https://dart.dev/tools/pub/automated-publishing
    name: Release (dart)
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup Dart SDK with JWT token https://github.com/dart-lang/setup-dart/blob/77b84bec90e9a0d07f68a3cedd3651ba9e606a12/.github/workflows/publish.yml#L33
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
      - run: dart pub get
        working-directory: ./dart
      - run: dev/dart/generate
      - run: dart test
        working-directory: ./dart
      - name: Set Tag
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Prepublish
        env:
          RELEASE_VERSION: ${{ env.GIT_TAG }}
        run: dev/dart/prepublish
      - name: Verify pubspec
        run: cat ./dart/pubspec.yaml
      - name: Publish
        run: dart pub publish --force
        working-directory: ./dart
